// <auto-generated />
using E.P.C.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E.P.C.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E.P.C.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("E.P.C.Models.AIO", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FanRPM")
                        .HasColumnType("int");

                    b.Property<int>("FanSize")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoiseLevel")
                        .HasColumnType("int");

                    b.Property<int>("PumpSpeed")
                        .HasColumnType("int");

                    b.Property<int>("RadiatorSize")
                        .HasColumnType("int");

                    b.Property<string>("SupportedSockets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("AIO_Brand");

                            t.Property("Model")
                                .HasColumnName("AIO_Model");

                            t.Property("NoiseLevel")
                                .HasColumnName("AIO_NoiseLevel");

                            t.Property("SupportedSockets")
                                .HasColumnName("AIO_SupportedSockets");
                        });

                    b.HasDiscriminator().HasValue("AIO");
                });

            modelBuilder.Entity("E.P.C.Models.CPU", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<float>("BaseClock")
                        .HasColumnType("real");

                    b.Property<float>("BoostClock")
                        .HasColumnType("real");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.ToTable("Products", t =>
                        {
                            t.Property("BoostClock")
                                .HasColumnName("CPU_BoostClock");

                            t.Property("Brand")
                                .HasColumnName("CPU_Brand");

                            t.Property("Model")
                                .HasColumnName("CPU_Model");

                            t.Property("SocketType")
                                .HasColumnName("CPU_SocketType");
                        });

                    b.HasDiscriminator().HasValue("CPU");
                });

            modelBuilder.Entity("E.P.C.Models.CPUFan", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<int>("Airflow")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoiseLevel")
                        .HasColumnType("int");

                    b.Property<int>("RPM")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("SupportedSockets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Airflow")
                                .HasColumnName("CPUFan_Airflow");

                            t.Property("Brand")
                                .HasColumnName("CPUFan_Brand");

                            t.Property("ConnectorType")
                                .HasColumnName("CPUFan_ConnectorType");

                            t.Property("Model")
                                .HasColumnName("CPUFan_Model");

                            t.Property("NoiseLevel")
                                .HasColumnName("CPUFan_NoiseLevel");

                            t.Property("RPM")
                                .HasColumnName("CPUFan_RPM");

                            t.Property("Size")
                                .HasColumnName("CPUFan_Size");
                        });

                    b.HasDiscriminator().HasValue("CPUFan");
                });

            modelBuilder.Entity("E.P.C.Models.Case", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriveBays")
                        .HasColumnType("int");

                    b.Property<int>("FanSlots")
                        .HasColumnType("int");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCPUCoolerHeight")
                        .HasColumnType("int");

                    b.Property<int>("MaxGPULength")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Case_Brand");

                            t.Property("FormFactor")
                                .HasColumnName("Case_FormFactor");

                            t.Property("Model")
                                .HasColumnName("Case_Model");
                        });

                    b.HasDiscriminator().HasValue("Case");
                });

            modelBuilder.Entity("E.P.C.Models.Fan", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<int>("Airflow")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoiseLevel")
                        .HasColumnType("int");

                    b.Property<int>("RPM")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Fan_Brand");

                            t.Property("Model")
                                .HasColumnName("Fan_Model");
                        });

                    b.HasDiscriminator().HasValue("Fan");
                });

            modelBuilder.Entity("E.P.C.Models.GPU", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<int>("BoostClock")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoreClock")
                        .HasColumnType("int");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemorySize")
                        .HasColumnType("int");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Ports")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TDP")
                        .HasColumnType("int");

                    b.Property<string>("dimensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("GPU_Brand");

                            t.Property("Chipset")
                                .HasColumnName("GPU_Chipset");

                            t.Property("Model")
                                .HasColumnName("GPU_Model");
                        });

                    b.HasDiscriminator().HasValue("GPU");
                });

            modelBuilder.Entity("E.P.C.Models.MotherBoard", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRAMCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RAMSlots")
                        .HasColumnType("int");

                    b.Property<string>("SocketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("MotherBoard_Brand");

                            t.Property("FormFactor")
                                .HasColumnName("MotherBoard_FormFactor");

                            t.Property("Model")
                                .HasColumnName("MotherBoard_Model");
                        });

                    b.HasDiscriminator().HasValue("MotherBoard");
                });

            modelBuilder.Entity("E.P.C.Models.PSU", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Connectors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EfficiencyRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Modular")
                        .HasColumnType("bit");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PSU");
                });

            modelBuilder.Entity("E.P.C.Models.RAM", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sticks")
                        .HasColumnType("int");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("RAM_Brand");

                            t.Property("Model")
                                .HasColumnName("RAM_Model");
                        });

                    b.HasDiscriminator().HasValue("RAM");
                });

            modelBuilder.Entity("E.P.C.Models.Storage", b =>
                {
                    b.HasBaseType("E.P.C.Models.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("connectionInterface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Storage_Brand");

                            t.Property("Capacity")
                                .HasColumnName("Storage_Capacity");

                            t.Property("FormFactor")
                                .HasColumnName("Storage_FormFactor");

                            t.Property("Model")
                                .HasColumnName("Storage_Model");

                            t.Property("Type")
                                .HasColumnName("Storage_Type");
                        });

                    b.HasDiscriminator().HasValue("Storage");
                });
#pragma warning restore 612, 618
        }
    }
}
